[package]
name = "seekust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }

[dev-dependencies]
tempfile = "3.8"

[[bin]]
name = "seekust"
path = "src/main.rs"
