name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: seekust
            asset_name: seekust-linux-amd64
          - os: macos-latest
            artifact_name: seekust
            asset_name: seekust-macos-amd64

    steps:
      - uses: actions/checkout@v4

      - name: Build binary
        run: cargo build --release

      - name: Test binary execution
        run: ./target/release/${{ matrix.artifact_name }}

      - name: Prepare binary
        run: |
          cd target/release
          strip ${{ matrix.artifact_name }}
          mv ${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Upload binary to versioned release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: target/release/${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary to latest release
        uses: softprops/action-gh-release@v1
        with:
          name: "Latest Release"
          tag_name: "latest"
          files: target/release/${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
