name: Release

on:
  workflow_dispatch: # Allows manual triggering
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: seekust
            asset_name: seekust-linux-amd64
          - os: macos-latest
            artifact_name: seekust
            asset_name: seekust-macos-amd64

    steps:
      - uses: actions/checkout@v4

      - name: Build binary
        run: cargo build --release

      - name: Prepare binary
        run: |
          cd target/release
          strip ${{ matrix.artifact_name }}
          mv ${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: target/release/${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-latest:
    name: Update Latest Tag
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update latest tag
        uses: softprops/action-gh-release@v1
        with:
          name: "Latest Release"
          tag_name: "latest"
          files: target/release/*
          prerelease: false
          draft: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
